version: '3.7'
services:
  app:
    build: .
    ports:
      - "8081:8080"  # No need to expose host ports here
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: todojsf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

